### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [metosin/clojure-bootcamp-setup#2]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/metosin/clojure-bootcamp-setup/blob/f1fc658bd6b32dec29faf6ea68fc31ffe304f2d0/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by miikka** [comment]
Thanks, fixed in https://github.com/metosin/clojure-bootcamp-setup/commit/652ad8c9fd056b6c2b25d1839f1fff6d388359ac.
